sudo: false

cache:
  yarn: true

install:
  - npm install -g elm elm-test@0.19.0-beta6 elm-format

script:
  - elm-format --validate src tests examples
  - elm-test
  - cd examples
  - elm make --output=/dev/null --debug src/Main.elm
